// angular-app/src/app/components/list-item/list-item.component.ts
import { Component, Input, OnChanges, OnInit } from '@angular/core';
import { Employee } from '../../interfaces/employee.interface';

@Component({
  selector: 'app-list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.css']
})
export class ListItemComponent implements OnInit, OnChanges {
  @Input()
  item: Employee | null = null;

  ngOnInit(): void {
    console.log('list item init');
  }

  ngOnChanges() {
    console.log('list item changes');
  }
}

<div *ngIf="item" [class]="['item', item.jobTitle]">
  <strong>{{ item.name }}</strong><br/>
  <span>Position: {{ item.jobTitle }}</span>&nbsp;---&nbsp;<span>Age: {{ item.age }}</span>
</div>

// react-app/src/components/body/list/listItem/listItem.tsx
import React from 'react'
import { Employee } from '../../../../interfaces/employee.interface'
import './listItem.css'
interface Props {
    employee: Employee
}
export const ListItem:React.FC<Props> = ({employee}) => {
    
const {age,jobTitle,name} = employee;

return (
    <div className={`item ${jobTitle}`}>
        <strong>{name }</strong><br/>
        <span>Position: { jobTitle }</span>&nbsp;---&nbsp;<span>Age: {age }</span>
    </div>
)}
