// angular-app/src/app/layout/footer/footer.component.ts
import { Component, EventEmitter, OnChanges, OnInit, Output } from '@angular/core';
import { DatasetSize } from '../../enums/dataset-size.enum';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit, OnChanges {
  @Output()
  makeAllBackend: EventEmitter<void> = new EventEmitter<void>();

  @Output()
  addItem: EventEmitter<void> = new EventEmitter<void>();

  @Output()
  removeItem: EventEmitter<void> = new EventEmitter<void>();

  @Output()
  numberOfItemsChanged: EventEmitter<any> = new EventEmitter<any>();

  DatasetSizes = DatasetSize;

  handleNumberOfItemsChange(event: any) {
    this.numberOfItemsChanged.emit(event.target.value)
  }

  ngOnInit(): void {
    console.log('footer init');
  }

  ngOnChanges() {
    console.log('footer changes');
  }
}

<div class="app-footer">
  <button (click)="makeAllBackend.emit()">Make all backend</button>
  <button (click)="addItem.emit()">Add item</button>
  <button (click)="removeItem.emit()">Remove item</button>

  <select (change)="handleNumberOfItemsChange($event)">
    <option>{{ DatasetSizes.TenItems }}</option>
    <option>{{ DatasetSizes.OneHundredItems }}</option>
    <option>{{ DatasetSizes.OneThousandItems }}</option>
    <option>{{ DatasetSizes.TenThousandsItems }}</option>
    <option>{{ DatasetSizes.TwentyThousandsItems }}</option>
  </select>
</div>

// react-app/src/components/footer/footer.tsx
import React from 'react';
import { dataMap } from '../../assets/data';
import {DatasetSize} from  '../../enums/dataset-size.enum';
import { JobTitle } from '../../enums/job-title.enum';
import { Employee } from '../../interfaces/employee.interface';
import './footer.css';

interface Props {
  data: Employee[]
  setData: (data: Employee[]) => any,
}

const makeAllBackend = (data:Employee[]) => {
  return data.map(el => ({...el, jobTitle: JobTitle.BackendDev}))
}

const addItem = (data:Employee[]) => {
  return [...data, data[0]]
}

const removeItem = (data:Employee[]) => {
  const [first, ...newData] = data
  return newData
}

export const Footer:React.FC<Props> =  ({setData, data}) => {


return(
<div className="app-footer">
  <button onClick={() => setData(makeAllBackend(data))}>Make all backend</button>
  <button onClick={() => setData(addItem(data))}>Add item</button>
  <button onClick={() => setData(removeItem(data))}>Remove item</button>
  <select onChange={(e) => setData(dataMap[e.currentTarget.value as DatasetSize])}  >
    <option>{ DatasetSize.TenItems }</option>
    <option>{ DatasetSize.OneHundredItems }</option>
    <option>{ DatasetSize.OneThousandItems }</option>
    <option>{ DatasetSize.TenThousandsItems }</option>
    <option>{ DatasetSize.TwentyThousandsItems }</option>
  </select>
</div>
)
}
